------------- DROP EXISTING TABLES -----------------
DROP SCHEMA IF EXISTS ESSEX;


--------------- CREATE BASE TABLES -----------------
CREATE SCHEMA ESSEX;
CREATE TABLE ESSEX.PROPERTIES (
    LATITUDE DECIMAL(24, 20),
    LONGITUDE DECIMAL(24, 20),
    PROPERTY_ADDRESS VARCHAR(100),
    CITY VARCHAR(100),
    STATE VARCHAR(2),
    ZIP VARCHAR(10),
    COUNTY VARCHAR(100),
    YEAR_BUILT INT,
    OCCUPIED_SPACE_COUNT INT,
    TOTAL_SPACE_COUNT INT,
    PARKING INT,
    EV_CHARGER INT,
    REDEVELOPMENT_OPPORTUNITIES TEXT,
    PRIMARY KEY(PROPERTY_ADDRESS,CITY,STATE,ZIP,COUNTY)
);